### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by mgehrls** [codercatdev/googleioextended#1]
My understanding is submitting issues should generally be specific and focused, but I'm new to working as a team on github so...

@codercatdev Would you mind taking a minute or two to just outline the workflow you would recommend for helping out here? I can google for specifics.

**Comment by codercatdev** [comment]
We are waiting to find out if Bevy will support a Virtual conference for us. If that is the case we will not use any of the video conferencing features in this app.

With that said what would be cool is to just start working on issues to make a cool splash screen all about our GDG GR event on May 10, 2023.

So I would create an issue and then list that issue in a PR to make a cool homepage.

I will create one and assign it to you :D

I reset the original project just to be a base install of Next.js.
